// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Bible Notes",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Bible Notes",
            targets: ["AppModule"],
            bundleIdentifier: "com.biblenotes.app",
            teamIdentifier: "D3MY6Q3AN9",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "App",
            resources: [
                // .process("Assets.xcassets") // Removed to avoid duplicate build file error
            ]
        )
    ]
)